### ISSUE TITLE
Subscription options for ignoring own messages does not work

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/minimq#128]
Even if the subscription option for ignoring your own messages is specified, it appears that the device may still receive them.

**Comment by ryan-summers** [comment]
Upon further investigation, this doesn't appear to be the case. Minimq is properly using the `no-local` flag, but there is a weird behavior between "local" and "retained" messages that were unexpected.

**Comment by jordens** [comment]
It's the spec being at unclear here. What exactly "forwarding" is and what it isn't is undefined (e.g. in regards to sending "old" retained messages at subscription time) and whether "Retain Handling" (=0) trumps "No Local" (=1): apparently it does.
