### ISSUE TITLE
No bounds on structs

### ISSUE THREAD

**Issue by jordens** [quartiq/minimq#162]
Unless absolutely necessary.

* https://github.com/quartiq/minimq/blob/2b8b2ee7ca03ff2a65d420437133d4395a1cbd80/src/mqtt_client.rs#L52
* https://github.com/quartiq/minimq/blob/2b8b2ee7ca03ff2a65d420437133d4395a1cbd80/src/mqtt_client.rs#L263-L268
* https://github.com/quartiq/minimq/blob/2b8b2ee7ca03ff2a65d420437133d4395a1cbd80/src/mqtt_client.rs#L677-L680
* https://github.com/quartiq/minimq/blob/2b8b2ee7ca03ff2a65d420437133d4395a1cbd80/src/config.rs#L19
* https://github.com/quartiq/minimq/blob/2b8b2ee7ca03ff2a65d420437133d4395a1cbd80/src/config.rs#L33

and others

ref https://stackoverflow.com/questions/49229332/should-trait-bounds-be-duplicated-in-struct-and-impl

**Comment by ryan-summers** [comment]
I think the only cleanup we can do is remove the `broker` bound because `Instant` has a bound on the construction parameter: https://docs.rs/embedded-time/latest/embedded_time/struct.Instant.html
