### ISSUE TITLE
[Question] Mqtt v3.1.1 compatibility

### ISSUE THREAD

**Issue by Ddystopia** [quartiq/minimq#165]
Hello, we are forced to communicate with mqtt v3.1.1 broker, but can't find any rust client for no_std. Is `minimq` capable of communicating with older broker? As far as I know, v5 brokers *can* communicate with v3.1.1 clients, but is it true in the opposite direction, for `minimq` ?

**Comment by ryan-summers** [comment]
It's not currently supported (but could be added). As far as I know, you'd have to intentionally remove the `properties` encoded into the message scheme. The actual binary API of the MQTT messages is a bit different between v3 and v5, so you'd have to ensure the messages going out could conform with the v3 API. We don't currently do that.

**Comment by ryan-summers** [comment]
Closing this as the question is answered. If you'd like to add MQTTv3 support, feel free to open an enhancement request and we can discuss it there :)
