### ISSUE TITLE
Client IDs less than maximum cause a panic

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/minimq#2]
When a client ID is provided in a connect packet that is less than the maximum client ID size, the library will panic because of array indexing bounds.

**Comment by eugeneia** [comment]
Should be fixed in https://github.com/quartiq/minimq/commit/f107e984ddeeff6a91e2389f60946b29ddbb6e2a#diff-0f0e0c38f74ecf78b5622ba6747f81b7L444-R444
