### ISSUE TITLE
Overly strict ClientID check (?)

### ISSUE THREAD

**Issue by dnadlinger** [quartiq/minimq#30]
Per https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901059:

> The Server MUST allow ClientID’s which are between 1 and 23 UTF-8 encoded bytes in length, and that contain only the characters "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ". The Server MAY allow ClientID’s that contain more than 23 encoded bytes. The Server MAY allow ClientID’s that contain characters not included in the list given above. 

This suggests that the client ID validation check https://github.com/quartiq/minimq/blob/8e537e2a584ca0e97fc0b37994f4e7c4878c0335/src/ser/serialize.rs#L26-L34 might be better left to the server.

**Comment by ryan-summers** [comment]
I was unaware that the server may optionally support additional client IDs - this code was originally written by someone else. Thanks for pointing this out! It very well may be better to leave this up to the server.

The downside is that a client ID that works on one broker may not work on another, which decreases portability.

That being said, we don't currently use client IDs for anything, and it's also an option to not specify a client ID at all and have the broker automatically assign one. As such, I would recommend we:
1. Keep the strict check (to enforce portability)
2. Allow users to not specify any client ID such that one is automatically assigned by the broker.

**Comment by jordens** [comment]
The strict check also decreases portability (from and to minimq).
I'd throw it out and let the broker decide. But supporting and preferring to have auto-assigned IDs is better still.
