### ISSUE TITLE
Choosing an MQTT protocol version family: v3 or v5

### ISSUE THREAD

**Issue by eugeneia** [quartiq/minimq#4]
Currently MQTT 5.0 is implemented, but I hadn’t given much thought to that decision. Right now deciding to conservatively go with the 3.x line is still a low-overhead option. I reckon we should discuss this and either cement or revert the choice to go with v5.

The main difference of the 5.x version line is the addition of attributes, which are a format for including metadata with messages. Prominently, v5 specifies a request/response pattern based on those attributes.

Looking at Stabilizer right now would suggest that we would benefit from the request/response pattern as that’s what Stabilizer’s network API does (receive new coefficients -> respond with OK/error).

However, it might also be that we don’t really need that. I could for example imagine a stabilizer that subscribes to *stabilizer/set* and publishes it’s settings to *stabilizer/get* (and possibly errors to *stabilizer/error*). Via MQTT message retention through the broker and QoS, a controller could set the coefficients and rely on the broker to deliver the setting to a stabilizer instance "on demand" (might be immediately, might be later when the stabilizer instance is power cycled etc).

Likewise, a controller would poll *stabilizer/get* and get the most recent setting (again, independent of whether stabilizer is on/off). Problems with the requested setting would show up in *stabilizer/error*.

There could be a *stabilizer/status* subject that is set to not retain messages which would be used to listen for the online/offline status of the stabilizer (no messages = offline, like a watchdog timer).

So it is at least imaginable to use the protocol in a way that does not involve a direct request/response relationship between the controller and stabilizer-like devices.

Advantages of sticking to v3 include:

- simplified implementation
- *maybe* less inter-version compatibility woes?

Advantages of implementing v5 besides the request/response pattern might include:

- if the the MQTT ecosystem ends up chasing v5 we might be in a good spot being there aready

WDYAT?

Cc @jordens @ryan-summers

**Comment by ryan-summers** [comment]
We can also just implement an informational publish for when a setting was rejected (e.g. to a logging interface). This would eliminate the need for a response since the log would indicate the setting change failed

_Note_: This precludes having automated, verified, API-like control of the settings unless we implement a log parser or define a custom API on top of MQTT. The script would have no idea if a settings change failed or not.

**Comment by jordens** [comment]
Then maybe it's good to differentiate between telemetry where we trust that the messages are valid (or else they are discarded) and setting updates that can fail where invalid messages need to be responded to. I agree that successful setting changes could then just be repeated as pub-sub telemetry. In that case, and if the pub-sub aspect is compatible between v3/v5 (thus handling my telegraf use case) it seems prudent to implement the req-resp properly. If v5 has an advantage there, then let's go for it.
I guess we still need the */get* style endpoints for req-resp then.
