### ISSUE TITLE
Add support for SessionState maintenance

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/minimq#42]
Utilize session states to maintain subscriptions through MQTT disconnections.

This will simplify user-side code so that management can be offloaded to the MQTT broker.

To do this, we will need to:
1. Store the client ID assigned to us by the broker (if none was provided)
2. Request saved session state on reconnections, clean session state on new connections

Additional comments:
* Should we allow subscription requests before the broker connects and temporarily store them internally until we can send the actual request?

**Comment by jordens** [comment]
Re client ID: If we use MQTT session state, then we should just use our own unique stable client IDs (maybe `sinara-${APP}-${MAC}`) and not use server-assigned ones.

I wouldn't buffer the subscription requests and let the application implement that instead.

**Comment by ryan-summers** [comment]
As a general comment, if we use stable client IDs, we'll need to append something like `-telemetry` based on which client it is, as we plan on utilizing multiple clients.

**Comment by jordens** [comment]
Agreed

**Comment by jordens** [comment]
If we go for stable unique IDs, we also should check that it doesn't lead to issues with stale tcp connections having to time out.
https://github.com/quartiq/stabilizer/issues/289#issuecomment-790878361
