### ISSUE TITLE
Generating client IDs, or: randomness in the embedded sphere

### ISSUE THREAD

**Issue by eugeneia** [quartiq/minimq#5]
MQTT uses client identifiers (short utf-8 byte strings) to disambiguate clients, and to uniquely identify client sessions (and their resumption/termination).

On a big server one would probably generate those randomly save for an application specific prefix without the danger of running into collisions. I have heard that getting random seeds on embedded devices can be tricky, so that might be an option for a typical device.

Also, while I haven’t looked specifically into it, I don’t think it is easy for clients to probe whether a given ID is in use. 

On a device like stabilizer, would we have the user flash each device with a unique client_id or something else?

**Comment by jordens** [comment]
The devices need to have (stable) unique IDs already for their MAC address and for their name (in the MQTT topic namespace). If the MQTT ID doesn't need to be ephemeral we can use either of those.

**Comment by ryan-summers** [comment]
Closing this for now. MQTT supports automatic assignment of client identifiers. If the client does not specify their own ID, the broker will automatically allocate an unused ID and assign it to the client as part of the connection sequence.
