### ISSUE TITLE
Update pings to be generated whenever no data received from broker

### ISSUE THREAD

**Issue by ryan-summers** [quartiq/minimq#53]
After further thought on [@dnadlinger's comment on Pull #52](https://github.com/quartiq/minimq/pull/52#issuecomment-900350932), it may be prudent to generate pings whenever we haven't received a control packet from the broker as well.

Thus, pings should be generated if either of the following conditions are met:
1. We have not sent a control packet within the keep-alive window
2. The broker hasn't sent a control packet in some pre-determined period

This will ensure we're properly checking even if the packet write fails, but the packet can't be sent for some reason (e.g. async transmission via external stack like the W5500).

**Comment by dnadlinger** [comment]
You pretty much had me convinced that the simplest option, just sending pings regularly on a timer, is appropriate, and any extra code to reset the timeout on other communication not worth the added complexity.

I guess one reason to care about the superfluous pings would be very power/traffic-constrained, deeply embedded systems?

**Comment by ryan-summers** [comment]
That's honestly not a bad assessment of the state of things. Sending an additional ~8 bytes ever keep-alive interval is some pretty negligible overhead, and the keep-alive functionality can be disabled by setting the interval to zero as well.

I'll have to give this some thought. Simpler code is always an advantage.
