### ISSUE TITLE
Connecting and publishing

### ISSUE THREAD

**Issue by mladedav** [quartiq/minimq#56]
Hi, I really like the library and I'm trying to use the master version (which I noticed is considerably different from 0.3 which is latest), but I can't seem to be able to publish. The problem seems to be in that the connection is never established, so all the publish calls are silently dropped (might I suggest logging that?) but I have not seen any API for connecting.

Can you point me to the correct function to establish a connection so that I can publish messages to a broker?

**Comment by mladedav** [comment]
For the record, I have found out that calling Minimq::poll() several times helps, but I believe there should be some other way to start the connection.

**Comment by ryan-summers** [comment]
Hi there @mladedav! The current design requires that `poll()` is called continuously in a low-priority task to execute the MQTT state machine. If `poll()` is not called regularly, the MQTT connection will not be established and `publish()` calls will be silently ignored.
