### ISSUE TITLE
Documentation improvements (make `mqtt_client` module public)

### ISSUE THREAD

**Issue by systec-ms** [quartiq/minimq#72]
Shouldn't be at least the `mqtt_client` module public
`pub mod mqtt_client;`?

This would also improve the docs since you can see the `MqttClient` struct and the implemented functions.

Alternately, `cargo doc --document-private-items` could be used to build the docs.

**Comment by ryan-summers** [comment]
You're correct - I was wondering why things were so funky on the docs. This module should indeed be public.
